### ISSUE TITLE
system->RJ return value

### ISSUE THREAD

**Issue by dschwen** [Argonne-National-Laboratory/neml#79] opened 2020-10-19 13:57 UTC
NEML has a pattern of passing up `ier` return status values up the call tree. This pattern is broken in `solvers.cxx` where teh return value of `system->RJ` is ignores in multiple places. 

I'd like to return a new error status (something like domain error or whatever you'd like to call it) if results are outside of a reasonable range of values and would result in fatal errors further down the line.

**Comment by dschwen** [comment] 2020-10-19 14:01
Looks like that omission will prevent substepping from cutting the step size. (but take this with a grain of salt, as I'm just starting to dig into the solve portion of NEML :-) )

**Comment by reverendbedford** [comment] 2020-10-19 14:14
1. If the solver isn't correctly passing back ier that would be a significant issue.  I just rewrote a large part of the solver system (it's on branch creep_integration).  That's ready to merge, I just need to poke someone here to review the PR.  I'll do that and if it's still an issue we definitely need to fix it.
2. I'm a little more hesitant to do a lot of detailed domain checking in routines that are going to get called a lot.  Normally if something like that goes wrong it's caused by a failed nonlinear solve, as there are mathematical reasons for a lot of the model options that should keep the values in a "reasonable" domain (radial return for the rate independent models).  But see #1, none of this helps if the solver is not reporting correctly.  But I can try it for a particular model and see how it affects performance.

**Comment by dschwen** [comment] 2020-10-19 14:53
Fair point. I'm talking about 

https://github.com/Argonne-National-Laboratory/neml/blob/dev/src/solvers.cxx#L76
https://github.com/Argonne-National-Laboratory/neml/blob/dev/src/solvers.cxx#L120
https://github.com/Argonne-National-Laboratory/neml/blob/dev/src/solvers.cxx#L127
https://github.com/Argonne-National-Laboratory/neml/blob/dev/src/solvers.cxx#L300

where the return value is ignored. I'll checkout your branch!

**Comment by reverendbedford** [comment] 2020-10-19 14:55
Hmm, yes that seems quite wrong...  I think I'll take advantage of the new solver branch to fix that...

**Comment by reverendbedford** [comment] 2020-10-19 19:30
@dschwen Try the updated dev branch please and let me know.

**Comment by dschwen** [comment] 2020-10-20 01:39
Seems better (It errors with a failed neml solve, which continues the moose solve).
The underlying issue (related to a common project with a certain private company) persists. I'm using a model which is entirely within the valid range of the neml model but I get failed NEML stress updates at a reproducible point in time and space.

**Comment by reverendbedford** [comment] 2020-10-20 12:50
Hmm you may need to send me some details (or example input) by email.  Unless it's using a linear elastic model or something like associative plasticity with a "nice" hardening model there are no guarantees that the nonlinear equations NEML sets up to integrate the model have a reachable solution for an arbitrary load step.

**Comment by dschwen** [comment] 2020-11-05 20:06
How would you feel about using exceptions instead of passing `ier` up the call chain?

**Comment by reverendbedford** [comment] 2020-11-05 20:11
1) Sorry, I will get to this.  I have a conference thing next week I need
to get some results wrapped up for.
2) Yes, I would like to switch to informative exceptions.  I made a poor
design decision when I started NEML to go with error codes.  The python
bindings already convert to exceptions for error handling on that side of
things.

Would it help if I start the return code -> exception conversion at the
highest level and throw an exception in NEML if the library utterly cannot
solve the time step?  i.e. if I exhaust all adaptive integration?  Or do
you need something finer grained right away?

**Comment by dschwen** [comment] 2020-11-05 21:29
Thanks Mark, this is more of a long term design suggestion, as it would simplify the NEML code a bit. Let me know if I can help.

**Comment by reverendbedford** [comment] 2022-04-20 18:57
Closed by #130

**Closed by reverendbedford** 2022-04-20 18:57 UTC
